Repository UBC-MDS/test-creation, pull requests merged in 2024-05, with the labels that each got.

#10 docs: record GPT 4 prompts, potentially for generating checklist
  img/compare_table_example.png
  img/gpt4_example.png
  img/grep_example.png
  src/gpt_4/README.md
Labels: documentation

#29 feat: Add example call to OpenAI API using LangChain
  .env.template
  .gitignore
  README.md
  environment.yml
  src/test_creation/test_creation.py
Labels: enhancement

#41 docs: Add a diagram as an overview for the system
  img/proposed_system_overview.png
  report/proposal/_build/.doctrees/environment.pickle
  report/proposal/_build/.doctrees/proposal.doctree
  report/proposal/_build/html/.buildinfo
  report/proposal/_build/html/_images/proposed_system_overview.png
  report/proposal/_build/html/_sources/proposal.ipynb
  report/proposal/_build/html/proposal.html
  report/proposal/_build/html/searchindex.js
  report/proposal/_build/jupyter_execute/proposal.ipynb
  report/proposal/proposal.ipynb
Labels: documentation

#44 docs: Add checklist with skeleton structure with a few generic cases
  checklist/checklist.yaml
Labels: documentation, enhancement

#37 feat: Script to extract the filescodes that contain the tests
  README.md
  environment.yml
  src/code_analyzer/example.py
  src/code_analyzer/modules/__init__.py
  src/code_analyzer/modules/analyzers/__init__.py
  src/code_analyzer/modules/analyzers/python.py
  src/code_analyzer/modules/repo.py
Labels: enhancement

#64 docs: Fix wrong surname-lastname order in references
  checklist/checklist.yaml
  checklist/references.bib
Labels: bug, documentation

#69 feat: Add functionalities to read and export the checklist in CSV format
  checklist/checklist.yaml
  src/checklist/checklist.py
Labels: documentation, enhancement

#40 feat: test completeness score
  environment.yml
  src/test_creation/01_explore-chatbot-and-doc-loader.ipynb
  src/test_creation/02_improve-accuracy.ipynb
  src/test_creation/03_add-checklist-evaluation.ipynb
  src/test_creation/04_refactor-code.ipynb
  src/test_creation/analyze.py
  src/test_creation/demo.ipynb
  src/test_creation/demo_prompt_eng.ipynb
  src/test_creation/modules/__init__.py
  src/test_creation/modules/checklist/__init__.py
  src/test_creation/modules/checklist/checklist.py
  src/test_creation/modules/code_analyzer/__init__.py
  src/test_creation/modules/code_analyzer/analyzers/__init__.py
  src/test_creation/modules/code_analyzer/analyzers/python.py
  src/test_creation/modules/code_analyzer/example.py
  src/test_creation/modules/code_analyzer/repo.py
Labels: enhancement

#65 docs: Add checklist items for model evaluation and testing
  checklist/checklist.yaml
  checklist/references.bib
Labels: documentation

#77 Updated demo.ipynb for system demonstration during presentation
  src/test_creation/demo.ipynb
  src/test_creation/demo_prompt_eng.ipynb
Labels: documentation

#81 feat: Refactor `analyze.py`; Add validation and retry logic; Handle no test case and/or checklist item
  .gitignore
  src/test_creation/analyze.py
  src/test_creation/modules/checklist/checklist.py
  src/test_creation/modules/llm_eval/consistency_eval.py
  src/test_creation/modules/workflow/__init__.py
  src/test_creation/modules/workflow/files.py
  src/test_creation/modules/workflow/parse.py
Labels: enhancement
